FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./

RUN npm ci

COPY . .

ARG NEXT_PUBLIC_API_BASE_URL=""
ARG NEXT_PUBLIC_API_VERSION=""
ARG NEXT_PUBLIC_API_TIMEOUT=""
ARG NEXT_PUBLIC_API_RETRY_ATTEMPTS=""
ARG NEXT_PUBLIC_API_DEBUG=""
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY=""
ARG NEXT_PUBLIC_SKIP_VERIFICATION_STEPS=""
ARG NEXT_PUBLIC_AUTH_SUCCESS_REDIRECT=""
ARG NEXT_PUBLIC_AUTH_REGISTER_REDIRECT=""
ARG NEXT_PUBLIC_WS_URL=""
ARG NEXT_PUBLIC_GIPHY_API_KEY=""

ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ENV NEXT_PUBLIC_API_VERSION=${NEXT_PUBLIC_API_VERSION}
ENV NEXT_PUBLIC_API_TIMEOUT=${NEXT_PUBLIC_API_TIMEOUT}
ENV NEXT_PUBLIC_API_RETRY_ATTEMPTS=${NEXT_PUBLIC_API_RETRY_ATTEMPTS}
ENV NEXT_PUBLIC_API_DEBUG=${NEXT_PUBLIC_API_DEBUG}
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
ENV NEXT_PUBLIC_SKIP_VERIFICATION_STEPS=${NEXT_PUBLIC_SKIP_VERIFICATION_STEPS}
ENV NEXT_PUBLIC_AUTH_SUCCESS_REDIRECT=${NEXT_PUBLIC_AUTH_SUCCESS_REDIRECT}
ENV NEXT_PUBLIC_AUTH_REGISTER_REDIRECT=${NEXT_PUBLIC_AUTH_REGISTER_REDIRECT}
ENV NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
ENV NEXT_PUBLIC_GIPHY_API_KEY=${NEXT_PUBLIC_GIPHY_API_KEY}

RUN npm run build
RUN npm prune --production

FROM node:20-alpine AS runner
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000
CMD ["npm", "start"]
