const MAX_TWEET_LENGTH = 260; //blue color
const MAX_WARNING_TWEET_LENGTH = 20; // yellow color
const MAX_RED_PROGRESS_STEPS = 10;
const MAX_ALLOWABLE_TWEET_LENGTH = MAX_TWEET_LENGTH + MAX_WARNING_TWEET_LENGTH;

export {
  MAX_TWEET_LENGTH,
  MAX_WARNING_TWEET_LENGTH,
  MAX_RED_PROGRESS_STEPS,
  MAX_ALLOWABLE_TWEET_LENGTH,
};
export const ADD_TWEET = {
  POST: 'POST' as const,
  REPLY: 'REPLY' as const,
  QUOTE: 'QUOTE' as const,
};
