const MAX_TWEET_LENGTH = 260; //blue color
const MAX_WARNING_TWEET_LENGTH = 20; // yellow color
const MAX_RED_PROGRESS_STEPS = 10;
export { MAX_TWEET_LENGTH, MAX_WARNING_TWEET_LENGTH, MAX_RED_PROGRESS_STEPS };
